name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Dev Dependencies Installation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      - name: Linter Flake8
        run:
          flake8

      - name: Tests Suite
        run:
          coverage run -m pytest tests --verbose

      - name: Min Test Coverage
        run:
          coverage report
