name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Dev Dependencies Installation
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Linter Flake
        run:
          poetry run flake8

      - name: Tests Suite
        run:
          poetry run coverage run -m pytest tests --verbose

      - name: Min Test Coverage
        run:
          poetry run coverage report
