name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Environment Setup
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Dev Dependencies Installation
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Linter Flake8
        run:
          poetry run flake8

      - name: Tests Suite
        run:
          poetry run coverage run -m pytest tests --verbose

      - name: Coveralls Push
        if: github.ref == 'refs/heads/feature/main'
        run:
          poetry run coveralls

      - name: Min Test Coverage
        run:
          poetry run coverage report
